apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pta9mprre-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pta9mprre-nodejs 
  name: pta9mprre-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pta9mprre-nodejs 
